### ISSUE TITLE
Unable to connect fivem server with cosmo installation

### ISSUE THREAD

**Issue by WEEZOOKARP** [tbdscripts/cosmo-fivem#1]
Server constantly unable to connect to site but players are able to join
![image](https://user-images.githubusercontent.com/76672483/145674217-1fc4a999-21a3-4c08-9021-377352a109c3.png)

errors in browser console
![image](https://user-images.githubusercontent.com/76672483/145674245-9a9c3937-6b63-4cff-975f-2ed0e840c224.png)

server config (attempted without the server/6 bit at the end and same result)
![image](https://user-images.githubusercontent.com/76672483/145674267-04d41153-12f2-4881-a99f-ad4b5d336586.png)

**Comment by WEEZOOKARP** [comment]
http://139.99.148.150:30120/info.json
it looks like it's trying to grab this and failing

**Comment by mexdeloo** [comment]
use the support channel
